### ISSUE TITLE
Дополнительные услуги

### ISSUE THREAD

**Issue by TiGR** [appwilio/cdek-sdk#13]
В документации к калькулятору содержится описание дополнительного поля `services`, который представляет собой массив с элементами из кода услуги и опционального дополнительного параметра услуги. В SDK я этого не нашёл. Может быть плохо искал?

**Comment by jhaoda** [comment]
Это поле появилось в версии 1.2, судя по документации, поэтому в SDK его нет.

**Comment by TiGR** [comment]
А планируется появление? Просто потребовалось добавлять услуги, вот думаю как это теперь лучше делать. Вас подождать или самому что-то придумывать?

**Comment by jhaoda** [comment]
@TiGR с удовольствием приму пулл-реквест :wink:

**Comment by jhaoda** [comment]
Спасибо!
