### ISSUE TITLE
Поддержка PHP 7.0

### ISSUE THREAD

**Issue by sanmai** [appwilio/cdek-sdk#15]
Можно ли понизить требования к версии PHP до текущей стабильной версии? Например, в Debian stable всё ещё есть только PHP 7.0.

У вас в проекте есть только два места где используется `void` и нигде не используется `iterable`. Есть несколько мест где объявлены публичные и приватные константы, но это тоже можно исправить без конфликтов. Ещё есть места с опциональными значениями, но это тоже поправимо. (Обычно всё кроме `iterable` проблемы не представляет.)

Никакие из собственных зависимостей не требуют PHP 7.1+, с этим тоже нет проблем.

Пока что получается так:
```
$ git diff -w --stat
 composer.json                           |  2 +-
 src/Common/City.php                     |  2 +-
 src/Common/Order.php                    | 10 +++++-----
 src/Common/Pvz.php                      |  2 +-
 src/Requests/CalculationRequest.php     | 12 ++++++------
 src/Requests/DeleteRequest.php          |  2 +-
 src/Requests/DeliveryRequest.php        |  4 ++--
 src/Requests/InfoReportRequest.php      |  4 ++--
 src/Requests/PrintReceiptsRequest.php   |  4 ++--
 src/Requests/PvzListRequest.php         | 10 +++++-----
 src/Requests/StatusReportRequest.php    |  4 ++--
 src/Responses/DeliveryResponse.php      |  2 +-
 src/Responses/PrintReceiptsResponse.php |  2 +-
 src/Responses/Types/Message.php         |  2 +-
 src/Responses/Types/Result.php          | 16 ++++++++--------
 15 files changed, 39 insertions(+), 39 deletions(-)
```

**Comment by TiGR** [comment]
Ничего не имею против расширения поддерживаемых версий PHP, даже всеми руками "за". Самому ради использования этой библиотеки пришлось обновить PHP на проде с 7.0 до 7.2, но просто одно замечание:

> Можно ли понизить требования к версии PHP до _текущей стабильной версии_?

Тут такое дело. 7.0 вышла в декабре 2015 и официальное окончание поддержки со стороны разработчиков PHP - декабрь 2018.

Хотя согласно [статистике](https://seld.be/notes/php-versions-stats-2018-1-edition), 7.0 ещё используется на 23% серверов с php, а 7.1+ на 55% серверов (по состоянию на май 2018). Если понизить требования до 7.0, число поддерживаемых серверов будет почти 80%.

**Comment by jhaoda** [comment]
~~@sanmai сделайте пулл-реквест, чтобы можно было оценить изменения предметно.~~
Отзываю своё предложение.

**Comment by greabock** [comment]
Нус... даунгрейды дело такое-себе. С другой стороны, зная ситуацию на российских серверах и хостингах, это уже не кажется таким уж странным. Думаю, что можно и понизить требование.

**Comment by jhaoda** [comment]
В свете практически релизнутого 7.3 не вижу в этом смысла. То, что дебиан тормоз, это печально, конечно.

**Comment by sanmai** [comment]
У меня есть сколько-то времени, оплаченного заказчиком, которое я могу потратить на работу по этому проекту. Например, можно добавить тестов, или подключить CI, исправить найденные ошибки. Для заказчика критически важна поддержка PHP 7.0, потому вопрос поддержки этой версии решает буду ли я работать над этим проектом, или буду делать всё то же самое в своём форке, от чего мало кому, кроме заказчика, будет какая-то польза.

Правильно ли я понимаю что мне следует идти по последнему варианту?

**Comment by jhaoda** [comment]
@sanmai да, форк это решение.

Не могли бы вы рассказать, почему поддержка РНР 7.0 так критически важна заказчику?

**Comment by sanmai** [comment]
Не поддержка, а работа под PHP 7.0 пока тот официально поддерживается. Причины есть, но обсуждать их нет смысла, я не в той позиции чтобы что-то здесь поменять, и, прямо скажем, мне это ограничение не мешает.

Форк уже в работе, вы не будете против добавить на него ссылку если что?

**Comment by greabock** [comment]
@sanmai как отметил @TiGR форк выглядит замечательно. Обсужу это дело с @jhaoda, ссылку обязательно добавим. Так держать 👍

**Comment by sanmai** [comment]
Очень буду рад ссылке, спасибо большое за поддержку начинания.
