### ISSUE TITLE
Номера версий

### ISSUE THREAD

**Issue by TiGR** [appwilio/cdek-sdk#3]
День добрый. Добавьте пожалуйста теги с номерами версий - это сильно ускоряет установки через composer.

**Comment by jhaoda** [comment]
@TiGR проект в стадии разработки, никаких версий ещё нет.

**Comment by greabock** [comment]
@jhaoda ну таки можно предрелизные 0.0.* проставить, например. Установку ускорит.

**Comment by jhaoda** [comment]
@TiGR @greabock сделал `v0.1`.
