### ISSUE TITLE
Открытие ветки beta-common-integration

### ISSUE THREAD

**Issue by volga** [appwilio/cdek-sdk#7]
В связи с наличием beta версии common-integration у СДЭК - предлагаю открыть новую ветку разработки beta-common-integration. СДЭК предоставил мне доступ к ней. Как таковой документации там еще не существует.

Первая необходимая правка в новой ветке:

- В тег ордер необходимо добавить данную информацию для изменения отправителя на третье лицо

```
<Sender company="РУ_ЕКАТЕРИНБУРГ_Мега_BCS" name="ООО Адидас">
            <address flat=" " house="-" street="620131, Екатеринбург, Металлургов,87  "/>
            <phone>8-800-250-04-05</phone>
</Sender>
```

Также в новой версии отличаются ответы.

Готов сделать первые правки для интеграции с бета версией в новой ветке.

**Comment by jhaoda** [comment]
Можно хоть где-то почитать об отличиях?

**Comment by volga** [comment]
Нет, почитать негде - в том то и дело.
Разработчики СДЭК мне сообщили на словах,, что ответы отличаются, документации нет.
Первое отличие в моем запросе - тег Sender.

Я, конечно, могу сделать форк и начать параллельную разработку - но хотелось бы делать это в одной точке.

**Comment by jhaoda** [comment]
@Volga делайте PR в мастер, я его потом в отдельную ветку замержу.

**Comment by volga** [comment]
#8 - @jhaoda, сделал

**Comment by greabock** [comment]
@Volga документация по api у них убогая. Большинство вещей делались "на ощупь". 
Скорее всего, где-то мне попалась дата именно в таком формате, и я по наивности своей решил, что у них единый формат дат. А может и не так это было - полтора года прошло.
Кстати, не удивлюсь если они поменяли формат и никому не сказали. За ними водится такое.

@jhaoda открой товарищу репу уже, пусть сделает ветку и пилит в нее. Что мы будем тут как индейцы с пулл-реквестами скакать? Тем более, что ни у меня ни у тебя полноценно занятся этим времени нет. Мужик адекватный же.

**Comment by volga** [comment]
Спасибо! Запрос закрываю.

**Comment by jhaoda** [comment]
@greabock ну шо ты, я просто заэтался :wink: Создал ветку, добавил в список доверенных.
